### ISSUE TITLE
v1.4.0 Build fails on linux against ffmpeg 4.4.1

### ISSUE THREAD

**Issue by lunik1** [meganz/MEGAcmd#523]
MEGAcmd v1.4.0 fails to build on Linux against ffmpeg 4.4.1, error is:
```
src/gfx/freeimage.cpp:191:18: error: 'AVStream' {aka 'struct AVStream'} has no member named 'skip_to_keyframe'
  191 |     videoStream->skip_to_keyframe = true;
      |                  ^~~~~~~~~~~~~~~~
```

The build succeeds against ffmpeg 4.3.2.

#231 might be related, but was reported long before ffmpeg 4.4.1 was released.

OS: NixOS, [but there are reports of the same issue on Arch Linux](https://aur.archlinux.org/packages/megacmd/).

**Comment by lunik1** [comment]
See also (possible duplicate of?) meganz/sdk#2576
